### ISSUE TITLE
Handle Server Errors (4xx and 5xx)

### ISSUE THREAD

**Issue by mahendra-shah** [navgurukul/oscar-fe#15]
#### Description:
- **4xx Errors:** Implement handling for "Daily quota exceeded" errors to provide clear user feedback and suggest next steps if applicable.
- **5xx Errors:** Ensure proper handling of "Server error: model overload" cases by adding retry mechanisms or fallback logic to improve user experience.

#### Acceptance Criteria:
- Users receive descriptive error messages for both 4xx and 5xx errors.
- The system gracefully retries or handles 5xx errors without crashing.

**Comment by surajsahani** [comment]
Fixed. tested from dev side
