### ISSUE TITLE
Microphone Stops Prematurely

### ISSUE THREAD

**Issue by Jayshri15** [navgurukul/oscar-fe#23]
Description: In the Oscar web app, the microphone stops after 30 seconds. In Keyboard and Flutter, it stops after 4-5 seconds without speech.

Steps to Reproduce:

1. Open the Oscar web app, Keyboard, or Flutter.
2. Start recording using the microphone.
3. Observe the recording duration without speech.

Actual Result:
Recording stops after 30 seconds (web) and 4-5 seconds (Keyboard, Flutter) without speech.

Expected Result:
The microphone should remain active for the full allowed duration, even without speech.

**Comment by Alpana2772** [comment]
Done
